spring.application.name=spring-boot-intro
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/spring_boot_intro
spring.datasource.username=root
spring.datasource.password=default123
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

